### PR TITLE
fix(runtimed): classify pool errors, show contextual banner messages

### LINKED ISSUE #1618: Conda warmup timeout shows misleading 'Invalid or unavailable package' error
## Problem

When a conda environment warmup times out, the UI displays:

> Invalid or unavailable package — Check package name in conda settings.

This is misleading — the packages are all valid and the solve completes successfully. The actual backend error is a **warmup timeout**, not an invalid package.

## What happened

From `runtimed.log`:

```
18:12:06 [INFO] runtimed::daemon: Solved: 172 packages to install
18:14:09 [ERROR] runtimed::daemon: Conda warmup timed out
18:14:24 [WARN] runtimed::daemon: Conda pool in backoff: 1 consecutive failures
         (Conda warmup failed (timed out or imports errored)), waiting 30s before retry.
         Check conda.default_packages in settings.
```

The solve succeeded, but the install/import verification phase timed out (likely transient network or disk slowness). The pool went into backoff and recovered on retry.

Settings had only standard packages — `pandas`, `numpy`, `matplotlib`, `pyarrow`, `seaborn` — all valid on conda-forge.

## Expected behavior

The UI should distinguish between:

1. **Invalid package** — solve fails because a package name doesn't exist or can't be resolved → show "Invalid or unavailable package" with the specific package name(s) that failed
2. **Timeout** — solve succeeds but install/warmup times out → show something like "Environment setup timed out — retrying" or "Conda environment is taking longer than expected"
3. **Import error** — environment created but imports fail → show which import failed

Right now all three cases collapse into the same generic message, which sends the user on a wild goose chase through their settings when nothing is actually wrong.

## Environment

- nteract Nightly `2.1.2-nightly.202604071916+ee5312c`
- macOS 26.3.1 (aarch64)

### PR DESCRIPTION
**Pull request by rgbkrk**
## Summary

Fixes the misleading "Invalid or unavailable package" error banner that appeared for **all** pool warming failures — including timeouts, import errors, and infra issues. The daemon now classifies errors with an `error_kind` field in the PoolDoc schema, and the frontend renders contextual messages based on the error type.

Closes #1618

## What changed

**Daemon (`crates/runtimed/src/daemon.rs`):**
- Added `error_kind` to `PackageInstallError` and `FailureState` structs
- Classified all ~25 `warming_failed_with_error` call sites into four categories: `timeout`, `invalid_package`, `import_error`, `setup_failed`
- Bumped timeouts: UV pip install/warmup and Conda warmup from 120s → 180s, pool env wait from 90s → 120s

**PoolDoc schema (`crates/notebook-doc/src/pool_state.rs`):**
- Added `error_kind: Option<String>` to `RuntimePoolState` with Automerge read/write support

**Frontend:**
- Added `error_kind` to TypeScript types in both `packages/runtimed` and `apps/notebook`
- `PoolErrorBanner` now renders contextually:

| Error kind | Banner message | Settings button? |
|---|---|---|
| `timeout` | "Environment setup timed out — Retrying automatically" | No |
| `invalid_package` | "Invalid or unavailable package — `{pkg}` — Check package name" | Yes |
| `import_error` | "Package import failed — Check package compatibility" | Yes |
| `setup_failed` | "Environment setup failed — Retrying automatically" | No |

## Verification

- [ ] Configure an invalid package in UV settings → banner shows "Invalid or unavailable package" with the package name and a Settings button
- [ ] Configure many heavy packages that cause warmup to take a long time → if it times out, banner shows "Environment setup timed out" with a clock icon, no Settings button
- [ ] After a transient failure resolves, banner clears on next successful warm
- [ ] Dismiss button still works for all error variants
- [ ] Tooltip on hover still shows the raw error message

_PR submitted by @rgbkrk's agent, Quill_

### CODE REVIEW

File: crates/runtimed/src/daemon.rs [hunk 1]
```diff
@@ -3379,6 +3409,7 @@ impl Daemon {
                 .warming_failed_with_error(Some(PackageInstallError {
```
Comment (rgbkrk) [inline crates/runtimed/src/daemon.rs]: Timeouts in the warmup step still get published as `import_error` here. The UV path distinguishes a timeout in [`daemon.rs#L3366-L3387`](https://github.com/nteract/desktop/blob/e22554cf70272ff29b490ef91308ac8c0bcd7f8f/crates/runtimed/src/daemon.rs#L3366-L3387), but the recorded failure at [`daemon.rs#L3403-L3413`](https://github.com/nteract/desktop/blob/e22554cf70272ff29b490ef91308ac8c0bcd7f8f/crates/runtimed/src/daemon.rs#L3403-L3413) always uses `error_kind: "import_error"`. The analogous Conda path does the same at [`daemon.rs#L2867-L2901`](https://github.com/nteract/desktop/blob/e22554cf70272ff29b490ef91308ac8c0bcd7f8f/crates/runtimed/src/daemon.rs#L2867-L2901). In practice, a real warmup timeout will still show the "Package import failed" banner with a Settings button instead of the new timeout banner.
